# Generated by Django 3.1.7 on 2021-05-25 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignedtask',
            fields=[
                ('checkername', models.CharField(max_length=200)),
                ('filelink', models.CharField(max_length=1000)),
                ('teamid', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Userdata',
            fields=[
                ('Decision', models.IntegerField()),
                ('Reason', models.TextField(max_length=1000)),
                ('Username', models.CharField(max_length=200)),
                ('Id', models.IntegerField(primary_key=True, serialize=False)),
                ('flink', models.CharField(default='', max_length=1000)),
            ],
        ),
    ]
