# Generated by Django 3.1.7 on 2021-05-26 15:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csiadmin', '0003_auto_20210525_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
